### ISSUE TITLE
app:fabAlignmentMode="end" makes all the buttons overlap in bottom app drawer.

### ISSUE THREAD

**Issue by pratyushtewari** [material-components/material-components-android-motion-codelab#7]
I am trying to set the FAB on the end alignment but it makes all the action buttons overlap on the nav button.

![InkedScreenshot_20201024-200807_LI](https://user-images.githubusercontent.com/251768/97096099-4c0e1080-1635-11eb-8ea3-6c327eda2c59.jpg)

**Comment by hunterstich** [comment]
Hey @pratyushtewari,

You'll probably have to manually hide the [chevron and logo](https://github.com/material-components/material-components-android-motion-codelab/blob/30d7e10bde40c0301c5ee1890b1c6307ccb86198/app/src/main/res/layout/activity_main.xml#L61-L87) from the `BottomAppBar` in `activity_main.xml`. Since those views are custom children inside `BottomAppBar`, the overflow menu doesn't know about them and can't avoid them in a dynamic way. 

The likely solution would be to do this yourself in [MainActivity#setBottomAppBarForEmail](https://github.com/material-components/material-components-android-motion-codelab/blob/complete/app/src/main/java/com/materialstudies/reply/ui/MainActivity.kt#L190-L200). We already hide the title in that method and you would likely want to do something similar, setting `bottomAppBarLogo` and `bottomAppBarChevron`'s visibility to `INVISIBLE` and then restoring their visibility in `MainActivity#setBottomAppBarForHome`.

Hope this helps
